[build]
  base ="/"
  command = "npm run build:prod"
  publish = "dist/browser"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "https://zonal-acceptance-production-f33c.up.railway.app/*"
to = "http://zonal-acceptance-production-f33c.up.railway.app/:splat"
status = 200
force = true
