/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Details { 
    air_pressure_at_sea_level?: number;
    air_temperature?: number;
    cloud_area_fraction?: number;
    relative_humidity?: number;
    wind_from_direction?: number;
    wind_speed?: number;
}

